apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-initcontainer
spec:
  volumes:
  - name: www
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: git
    image: alpine
    command: ["sh", "-c", "apk add git && git clone https://github.com/octocat/Spoon-Knife /www"]
    volumeMounts:
    - name: www
      mountPath: /www/
