apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2023-05-15T21:11:27Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "195960"
  uid: 09fab795-fb25-4f0e-aeaf-1ac4b46bd538
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
