apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-07T22:26:19Z"
  generation: 1
  labels:
    app: hasher
  name: hasher
  namespace: dockercoins
  resourceVersion: "137733"
  uid: 1dc0dc74-df99-4282-a957-1d2356083a83
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hasher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasher
    spec:
      containers:
      - image: dockercoins/hasher:v0.1
        imagePullPolicy: IfNotPresent
        name: hasher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}