apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-07T22:30:49Z"
  generation: 1
  labels:
    app: worker
  name: worker
  namespace: dockercoins
  resourceVersion: "138121"
  uid: c6d0b7de-b24c-4464-93e9-f9e7f0ca6b00
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: dockercoins/worker:v0.1
        imagePullPolicy: IfNotPresent
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}