apiVersion: v1
kind: Pod
metadata:
  name: init-tester
  labels:
    app: inittest
spec:
  containers:
  - name: webservice
    image: nginx
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
  initContainers:
  - name: failed
    image: busybox
    command: [/bin/true]
