apiVersion: v1
kind: Pod
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  volumes:
  - name: config
    configMap:
      name: haproxy
  containers:
  - name: haproxy
    image: haproxy
    volumeMounts:
    - name: config
      mountPath: /usr/local/etc/haproxy/
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
